name: Deploy to Virtual Cloud Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: Production

    steps:
      - name: Deploy
        run: cd ~/discord-bot && git pull && ./deploy.sh
