name: Deploy to Virtual Cloud Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: Production

    steps:
      - name: Deploy
        run: cd $APP_PATH && git pull && ./deploy.sh
        env:
          APP_PATH: ${{ secrets.APP_PATH }}
