name: Deploy to Virtual Cloud Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production

    env:
      SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

    steps:
      - name: SSH Setup
        run: |
          chmod -R 700 ~/
          mkdir -p ~/.ssh/
          ssh-keyscan -p $SERVER_PORT -t rsa $SERVER_ADDRESS >> ~/.ssh/known_hosts
          chmod -R 700 ~/.ssh

      - name: Deploy
        run: |
          echo $SERVER_SSH_KEY > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key -p $SERVER_PORT $SERVER_USER@$SERVER_ADDRESS "cd $APP_PATH && git pull && ./deploy.sh"
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
